# Configuration Settings for C94-M8P device
ublox_gps_node_rover:
  ros__parameters:
    debug: 2                    # Range 0-4 (0 means no debug statements will print)
    device: /dev/gps_rover
    #device: /dev/ttyACM1
    frame_id: gps_rover
    uart1:
        baudrate: 460800
        in: 35
        out: 3

    config_on_startup: false
    rate: 1.0                   # Measurement rate in Hz

