points_goal:     
  ros__parameters:
    goal_points: [  2.30, -25.57,
                    5.56, -25.56,
                    0.25,  16.27,
                    4.13 , 16.72,
                    6.17, 21.44,
                    -1.45 , 27.5,
                    -4.29 , -1.83,
                    2.9 , -4.96,
                    -12.33,26.49,
                    -17.36,10.3,
                    -34.44,3.0,
                    -43.30,2.4,
                    -44.08,12.72,
                    -34.94,19.79,
                    -23.82,-6.7,
                    -14.67,-10.89,
                    -15.92,-23.91,
                    -30.79,-19.27,
                    -42.65,-15.50]
    republish_hz: 2.0      # frecuencia a la que re‑publica la meta activa