external_url: 'udpm://239.255.76.1:5004?ttl=3'
broadcast_url: 'udpm://224.0.0.7:5006?ttl=1'

#From external device to the platform
######   Header2   ######
header2:
  component_id: 100
  vehicle_id: -1299645807
  station_id: -1212110460
  sequence_id: 0
  timestamp: 0.0

######   DiscreteDevice   ######
discrete_device:
  subsystem: 0
  automatic: False

######    RequestConnection   ######
request_connection:
  forced: True

