ARGJ801:
  global_parameters:
    global_parameter_name: "global_value"
    cmd_vel_topic_name: "cmd_vel"
    secured_cmd_vel_topic_name: "secured_cmd_vel"
    joystick_topic_name: "joy"
    gps_topic: "/fixposition/navsatfix"
    ll_path_topic: "ll_path"
    local_path_topic: "local_path"
    local_trajectory_topic: "local_trajectory"
    robot_frame: "FP_POI"
    local_fixed_frame: "FP_ENU0"
    global_fixed_frame: "ECEF"
    velodyne_frame: 'velodyne_link'
    sick_frame: 'sick_link'
    dead_man_button: 5
    x_axis_button: 1
    z_axis_button: 3 
    x_multiplier: 1.0
    z_multiplier: 1.0
    fsm:
      change_fsm_mode_srv_name: 'change_fsm'
      get_fsm_srv_name: "get_fsm_mode"
      get_fsm_topic_name: "fsm_mode"
      get_possible_transition_srv_name: "get_possible_transitions"
      get_possible_transition_topic_name: "possible_transitions"

  teleoperation_node:
    max_joy_msg_delay: 1.0
    queue_size: 10

  path_record_node:
    distance_between_record_points: 1.0

  path_following_node:
    path_service_name: 'get_fix_frame_path'
    path_params:
      look_points_ahead: 15
    target_distance: 30.0
    node_frequency: 10.0
    
  controller_node:
    type: "dynamic_la_pure_pursuit" 
    controller_frequency: 100.0
    min_speed: 0.5
    breaking_acc: 1.0
    pure_pursuit:
      K_ang_err: 0.2
      K_linear_err: 0.2
      v_forward: 1.0
      l_ahead: 3.0
      point_window_size: 40
    regulated_pure_pursuit:
      v_forward: 0.5
      l_ahead: 1.0
      r_min: 3.0
    dynamic_pp:
      look_ahead_distance: 2.0
      max_speed: 3.0
      max_ang_acc: 0.4
      max_ang_dec: 2.0
      max_lin_acc: 0.52
      max_lin_dec: 2.0
    dynamic_la_pp:
      look_ahead_v_gain: 2.0
      max_speed: 3.0
      max_ang_acc: 0.4
      max_ang_dec: 2.0
      max_lin_acc: 0.52
      max_lin_dec: 2.0
      min_speed: 0.5

  path_manager_node:
    localization_method: "Fixposition"
    read_path_service: "read_path_file"
    return_path_service: "get_robot_Path"
    write_path_service: "write_path_file"
    get_ll_path_service: "get_ll_path"
    fixed_frame_topic: "fixed_frame_topic"
    ll_path_topic: "ll_path"

  mpc_node:
    test_param: "lllllll"
    node_frequency: 50.0
    odometry_topic: "/fixposition/odometry_enu"

  argj801_ctrl_platform_node:
    kinematic_parameters:
      efective_radius : 0.295
      xICR : 0.70
      throttle_to_percent : 3.9276
      steer_to_percent : 17.2790
      component_id : 100
      vehicle_id : -1299645807
      station_id :  -1212110465
    arduino_params:
      port:  "/dev/ttyUSB0"
      watchdog_active: true
    lcm_params:
      lcm_config_file:  "argj801_lcm_config_platform.yaml"
    throttle_topic_name: "cmd_throttle_msg"
    self_test_active: false

  security_check_node:
    lidar_topic: "weighted_scan"
    dissable_service_name: "enable_security_check"
    threshold_1: 1.0
    threshold_2: 3.0
    factor: 0.25
    threshold_path: 1.5
    get_security_check_srv_name: "get_security_check"
    password_check_srv_name: "security_password_check"
    min_distance_to_path_topic_name: "min_distance_to_path"

  andoid_server_node:
    host: '0.0.0.0'
    port: 5001
    emergency_topic: '/Human/emergency_call'
    human_gps_fix_topic: '/Human/gps/fix'

  laser_segmentation:
    distance_threshold: 0.30
    max_avg_distance_from_sensor: 20.0
    max_points_segment: 200
    max_segment_width: 10.0
    method_threshold: ''
    min_avg_distance_from_sensor: 0.0
    min_points_segment: 3
    min_segment_width: 0.2
    noise_reduction: 0.3
    restore_defaults: false
    scan_topic: sick_scan
    segmentation_type: jump_distance_merge
    segments_topic: segments
    side_vision_limit: 30.0
    weight_factor: 0.6
    angle_increment: 0.0174533
    range_min: 0.1
    range_max: 10.0
    buffer_size: 20
    detection_threshold: 10
    spatial_threshold: 0.1
    inner_zone_angle: 30.0
    middle_zone_angle: 60.0

  argj801_sensors:
    lcm_params:
      lcm_config_file: 'argj801_lcm_config_sensors.yaml'
    velodyne: True
    sick: True
    left_telemetry: True
    right_telemetry: True
    odometer: True
    twist: True
    
  fixposition_driver_ros2:
    fp_output:
      formats: ["ODOMETRY", "LLH", "RAWIMU", "CORRIMU", "TF"]
      type: "tcp"
      port: "21000"
      ip: "192.168.1.17"
      rate: 200
      reconnect_delay: 5.0
    customer_input:
      speed_topic: "/fixposition/speed"

