ARGJ801:
  global_parameters:
    robot_frame: 'FP_POI'
    velodyne_frame: 'velodyne_link'
    sick_frame: 'sick_link'

  argj801_sensors:
    lcm_params:
      lcm_config_file: 'argj801_lcm_config_sensors.yaml'
    velodyne: True
    sick: True
    left_telemetry: True
    right_telemetry: True
    odometer: True
    twist: True
    camera: False
    camera_url: ''
    camera_frame: 'camera_link'
    image_compression_ratio: 75
    resize_image: False