octomap_server:
  ros__parameters:
    # --- geometría básica ---
    frame_id:               map
    resolution:             1000.0          # igual que antes
    sensor_model:
      max_range:            40.0           # tu Velodyne
      hit:                  0.65           # ↓ pega un poco menos
      miss:                 0.98           # ↑ limpia antes
      min:                  0.10           # ↓ umbral para pasar a libre
      max:                  0.97

    # --- para refrescar más deprisa ---
    compress_map:           false          # no prune cada ciclo
    incremental_2D_projection: true        # sólo proyecta lo nuevo
    filter_speckles:        true           # quita voxels sueltos

    # --- asegúrate de no recortar los rayos ---
    point_cloud_min_z:     -3.0
    point_cloud_max_z:      10.0
