points_goal:     
  ros__parameters:
    goal_points: [  -4.0,-22.0,4.0,
                    -12.85,14.68,0.8,
                    11.0,-22.0,1.62,
                    13.0,16.0,3.13,
                    32.0,-23.0,6.2,
                    32.0,17.0,0.0,
                    4.0,-26.0,1.7
                    ]

    republish_hz: 2.0      # frecuencia a la que re‑publica la meta activa